name: Code Redundancy Check

on: [push]

jobs:
  RedundancyCheck:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch transformers faiss-cpu

      # Step 4: Run the redundancy check script
      - name: Run redundancy check
        run: python scripts/redundancy_check.py
